#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Class-ErrorHandler
Version  : 0.04
Release  : 17
URL      : https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Class-ErrorHandler-0.04.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Class-ErrorHandler-0.04.tar.gz
Summary  : 'Base class for error handling'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Class-ErrorHandler-license = %{version}-%{release}
Requires: perl-Class-ErrorHandler-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
# NAME
Class::ErrorHandler - Base class for error handling
# SYNOPSIS
package Foo;
use base qw( Class::ErrorHandler );

%package dev
Summary: dev components for the perl-Class-ErrorHandler package.
Group: Development
Provides: perl-Class-ErrorHandler-devel = %{version}-%{release}
Requires: perl-Class-ErrorHandler = %{version}-%{release}

%description dev
dev components for the perl-Class-ErrorHandler package.


%package license
Summary: license components for the perl-Class-ErrorHandler package.
Group: Default

%description license
license components for the perl-Class-ErrorHandler package.


%package perl
Summary: perl components for the perl-Class-ErrorHandler package.
Group: Default
Requires: perl-Class-ErrorHandler = %{version}-%{release}

%description perl
perl components for the perl-Class-ErrorHandler package.


%prep
%setup -q -n Class-ErrorHandler-0.04
cd %{_builddir}/Class-ErrorHandler-0.04

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Class-ErrorHandler
cp %{_builddir}/Class-ErrorHandler-0.04/LICENSE %{buildroot}/usr/share/package-licenses/perl-Class-ErrorHandler/4363ec27cb3d61f19d5a018b005953777b5abec8
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Class::ErrorHandler.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Class-ErrorHandler/4363ec27cb3d61f19d5a018b005953777b5abec8

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.30.2/Class/ErrorHandler.pm
